In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Reddit Whisky Network Review Archive - Review Archive.csv')

In [3]:
data

,Timestamp,Whisky Name,Reviewer's Reddit Username,Link To Reddit Review,Reviewer Rating,Whisky Region or Style,Full Bottle Price Paid,Date of Review
0,NaN,100 Pipers,ExeTheHero,https://www.reddit.com/r/Scotch/comments/v719p...,0.01,Blend,20,06/07/22
1,12/14/2012 10:03:18,100 Pipers,merlinblack,http://www.reddit.com/r/Scotch/comments/14uder...,68,Blend,NaN,12/14/12
2,NaN,1792 12 Year,ArcadianWaheela,https://www.reddit.com/r/bourbon/comments/t68i...,,Bourbon,$49,03/03/22
3,10/26/2019 17:19:55,1792 12 Year,atxbourbon,https://www.reddit.com/r/bourbon/comments/dgyb...,70,Bourbon,$50,10/12/19
4,NaN,1792 12 Year,eagle_bonanza01,https://www.reddit.com/r/bourbon/comments/vik4...,85,Bourbon,52,06/22/22
...,...,...,...,...,...,...,...,...
53428,NaN,Glenturret Ruadh Maor 9 2013 SMWS 16.88 “Dress...,the_muskox,https://www.reddit.com/r/Scotch/comments/18m3b...,77,Highlands,NaN,12/19/23
53429,NaN,Glenallachie 9 2012 Cuvee Cask Finish,the_muskox,https://www.reddit.com/r/Scotch/comments/18mwc...,72,Speyside,NaN,12/20/23
53430,NaN,Loch Lomond 14,the_muskox,https://www.reddit.com/r/Scotch/comments/18nnt...,85,Highlands,$90 CAD,12/21/23
53431,NaN,Balblair 15,the_muskox,https://www.reddit.com/r/Scotch/comments/18pay...,75,Highlands,NaN,12/23/23
53432,NaN,Port Charlotte Islay Barley 2013,the_muskox,https://www.reddit.com/r/Scotch/comments/18pyb...,85,Islay,NaN,12/24/23

In [4]:
data[data['Whisky Name'] == "Blanton's Original Single Barrel"]

,Timestamp,Whisky Name,Reviewer's Reddit Username,Link To Reddit Review,Reviewer Rating,Whisky Region or Style,Full Bottle Price Paid,Date of Review
8509,NaN,Blanton's Original Single Barrel,2bullets4Toby,https://www.reddit.com/r/bourbon/comments/ro7a...,85,Bourbon,NaN,12/25/21
8510,NaN,Blanton's Original Single Barrel,aboutthatbarrel,https://www.reddit.com/r/bourbon/comments/u7xo...,,Bourbon,NaN,04/20/22
8511,NaN,Blanton's Original Single Barrel,adunitbx,https://www.reddit.com/r/bourbon/comments/10yv...,83,Bourbon,160,02/10/23
8512,8/17/2013 10:20:23,Blanton's Original Single Barrel,Allumina,http://www.reddit.com/r/bourbon/comments/1kjvx...,87,Bourbon,NaN,8/17/2013
8513,NaN,Blanton's Original Single Barrel,AlucardRises,https://www.reddit.com/r/bourbon/comments/112f...,82,Bourbon,NaN,02/14/23
...,...,...,...,...,...,...,...,...
8617,NaN,Blanton's Original Single Barrel,whiskytrails,https://www.reddit.com/r/bourbon/comments/v0rm...,87,Bourbon,$65,05/29/22
8618,12/20/2012 20:53:26,Blanton's Original Single Barrel,Zillah1985,http://www.reddit.com/r/bourbon/comments/157dq...,90,Bourbon,NaN,12/20/2012
8619,NaN,Blanton's Original Single Barrel,zSolaris,https://www.reddit.com/r/bourbon/comments/e7u3...,74,Bourbon,NaN,12/08/19
8640,NaN,Blanton's Original Single Barrel,RAstrong12,https://www.reddit.com/r/bourbon/comments/145a...,90,Bourbon,NaN,06/09/23
53393,NaN,Blanton's Original Single Barrel,the_muskox,https://www.reddit.com/r/bourbon/comments/184e...,80,Bourbon,NaN,11/26/23

In [5]:
master = pd.read_csv("src/data/master_bourbon_list.csv")
master

,bourbon_name,min_corn,max_corn,min_wheat,max_wheat,min_rye,max_rye,min_barley,max_barley,proof,min_age,max_age,rating
0,Blanton's Single Barrel,75,75,0,0,12,15,10,13,93,6,8,8